version: '3.7'

services:

  web:
    build: ./images/python
    container_name: picasso_server
    restart: always
    volumes:
      - ./..:/picasso
      - ./../storage/static:/picasso/storage/static
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:12
    container_name: picasso_postgresql
    volumes:
      - ./images/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.dev
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./.env.dev
    ports:
      - "16543:80"
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db


  nginx:
    build: ./images/nginx
    container_name: picasso_nginx
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./../storage/static:/static
    depends_on:
      - web


volumes:
  postgres_data:
